### ISSUE TITLE
The train.py dosen't support dataset XLong

### ISSUE THREAD

**Issue by Woolseyyy** [alimamarankgroup/HPMN#2]
It is very strange that train.py only supports training on Taobao and Amazon while hpmn.py supports all. Do I miss something?

**Comment by qinjr** [comment]
Thanks for the notification. It is fixed now.
It is because the XLong dataset was not available at the time that train.py is open sourced, so we masked the code for XLong at that time.

**Comment by Woolseyyy** [comment]
Thank you!
